export const FETCH_ALL_INSTALLATION = "FETCH_ALL_INSTALLATION";

export const FETCH_CODE_INSTALLATION = "FETCH_CODE_INSTALLATION";

export const FETCH_CODE_EQUIPEMENT = "FETCH_CODE_EQUIPEMENT";

export const FETCH_CODE_ACTIVITE = "FETCH_CODE_ACTIVITE";
