export const FETCH_ALL_INSTALLATION = "FETCH_ALL_INSTALLATION";

export const FETCH_CODE_INSTALLATION = "FETCH_CODE_INSTALLATION";

export const FETCH_CODE_EQUIPEMENT = "FETCH_CODE_EQUIPEMENT";

export const FETCH_CODE_ACTIVITE = "FETCH_CODE_ACTIVITE";

export const SET_CODE_INSTALLATION = "SET_CODE_INSTALLATION";

export const SET_CODE_EQUIPEMENT = "SET_CODE_EQUIPEMENT";

export const GET_CODE_POSTAL = "GET_CODE_POSTAL";

export const SELECT_BY_CODE_POSTAL = "SELECT_BY_CODE_POSTAL";
